<?php

########################################################################
# Extension Manager/Repository config file for ext: "clubdirectory"
#
# Auto generated by Extension Builder 2013-04-03
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Club Directory',
    'description' => 'clubdirectory',
    'category' => 'plugin',
    'author' => 'Stefan Froemken',
    'author_email' => 'projects@jweiland.net',
    'author_company' => 'jweiland.net',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '0.2.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '8.7.0-8.7.99',
            'maps2' => '2.6.0'
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        )
    )
);
