services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Clubdirectory\:
    resource: '../Classes/*'

  JWeiland\Clubdirectory\Helper\PathSegmentHelper:
    public: true
    arguments:
      - null
