services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Clubdirectory\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Called by makeInstance in TYPO3's PluginPreview
  JWeiland\Clubdirectory\Backend\Preview\ClubDirectoryPluginPreview:
    public: true

  # Called by makeInstance in our FrontendUser domain model
  JWeiland\Clubdirectory\Domain\Repository\FrontendUserRepository:
    public: true

  # Called by makeInstance in our ClubController
  JWeiland\Clubdirectory\Helper\HiddenObjectHelper:
    public: true
