services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Clubdirectory\:
    resource: '../Classes/*'

  JWeiland\Clubdirectory\Helper\PathSegmentHelper:
    public: true
    arguments:
      - null

  JWeiland\Clubdirectory\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Clubdirectory\Event\PostProcessFluidVariablesEvent

  JWeiland\Clubdirectory\EventListener\AddGlossaryEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Clubdirectory\Event\PostProcessFluidVariablesEvent
      after: JWeiland\Clubdirectory\EventListener\AddPaginatorEventListener

  JWeiland\Clubdirectory\EventListener\AllowSearchParameterEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Clubdirectory\Event\PreProcessControllerActionEvent
